apiVersion: v1
kind: Service
metadata:
  labels:
    app: product-service
  name: product-service
spec:
  ports:
    - port: 8091
      targetPort: 8091
  type: LoadBalancer
  selector:
    app: product-service-v2
#  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-v2
  labels:
    app: product-service-v2
spec:
  selector:
    matchLabels:
      app: product-service-v2
  replicas: 1
  template:
    metadata:
      labels:
        app: product-service-v2
      name: product-service-v2
    spec:
      containers:
        - image: parthsanaja/product-service-v2:1
          name: product-service-v2
          ports:
            - containerPort: 8091