apiVersion: v1
kind: Service
metadata:
  labels:
    app: order-service
  name: order-service
spec:
  ports:
    - port: 8090
      targetPort: 8090
  type: LoadBalancer
  selector:
    app: order-service-v2
#  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-v2
  labels:
    app: order-service-v2
spec:
  selector:
    matchLabels:
      app: order-service-v2
  replicas: 1
  template:
    metadata:
      labels:
        app: order-service-v2
      name: order-service-v2
    spec:
      containers:
        - image: parthsanaja/order-service:4
          name: order-service-v2
          ports:
            - containerPort: 8090
          envFrom:
            - configMapRef:
                name: "order-service-config1"