apiVersion: v1
kind: Service
metadata:
  labels:
    app: userdb
  name: userdb-service
spec:
  ports:
    - port: 5432
      targetPort: 5432
#  type: LoadBalancer
  selector:
    app: userdb
#  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userdb
  labels:
    app: userdb
spec:
  selector:
    matchLabels:
      app: userdb
  replicas: 1
  template:
    metadata:
      labels:
        app: userdb
      name: userdb-service
    spec:
      containers:
        - image: postgres
          name: userdb
          env:
            - name: "POSTGRES_USER"
              value: "admin"
            - name: "POSTGRES_PASSWORD"
              value: "admin"
            - name: "POSTGRES_DB"
              value: "userdb"
          ports:
            - containerPort: 5432