apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-service
  name: user-service
spec:
  ports:
    - port: 8092
      targetPort: 8092
  type: LoadBalancer
  selector:
    app: user-service-v2
#  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-v2
  labels:
    app: user-service-v2
spec:
  selector:
    matchLabels:
      app: user-service-v2
  replicas: 1
  template:
    metadata:
      labels:
        app: user-service-v2
      name: user-service-v2
    spec:
      containers:
        - image: parthsanaja/user-service-v2:3
          name: user-service-v2
          ports:
            - containerPort: 8092
          envFrom:
            - configMapRef:
                name: user-service-config1